<?php

return [
    'route_labels' => [
        'activity-logs.index' => 'Viewed Activity Logs',
        'logout' => 'Logged Out',

        'users.index' => 'Viewed Users',
        'users.create' => 'Opened Create User',
        'users.store' => 'Created User',
        'users.edit' => 'Opened Edit User',
        'users.update' => 'Updated User',
        'users.destroy' => 'Deleted User',

        'roles.index' => 'Viewed Roles',
        'roles.create' => 'Opened Create Role',
        'roles.store' => 'Created Role',
        'roles.edit' => 'Opened Edit Role',
        'roles.update' => 'Updated Role',
        'roles.destroy' => 'Deleted Role',

        'permissions.index' => 'Viewed Permissions',
        'permissions.create' => 'Opened Create Permission',
        'permissions.store' => 'Created Permission',
        'permissions.edit' => 'Opened Edit Permission',
        'permissions.update' => 'Updated Permission',
        'permissions.destroy' => 'Deleted Permission',

        'teams.index' => 'Viewed Teams',
        'teams.create' => 'Opened Create Team',
        'teams.store' => 'Created Team',
        'teams.edit' => 'Opened Edit Team',
        'teams.update' => 'Updated Team',
        'teams.destroy' => 'Deleted Team',

        'organisations.index' => 'Viewed Organisations',
        'organisations.create' => 'Opened Create Organisation',
        'organisations.store' => 'Created Organisation',
        'organisations.edit' => 'Opened Edit Organisation',
        'organisations.update' => 'Updated Organisation',
        'organisations.destroy' => 'Deleted Organisation',

        'projects.index' => 'Viewed Projects',
        'projects.create' => 'Opened Create Project',
        'projects.store' => 'Created Project',
        'projects.edit' => 'Opened Edit Project',
        'projects.update' => 'Updated Project',
        'projects.destroy' => 'Deleted Project',

        'bom.index' => 'Viewed BOMs',
        'bom.create' => 'Opened Upload New BOM',
        'bom.store' => 'Uploaded New BOM',
        'bom.edit' => 'Opened Edit BOM',
        'bom.update' => 'Updated BOM',
        'bom.updateBOM' => 'Updated BOM',
        'bom.verify' => 'Verified BOM Template',
        'bom.filter' => 'Viewed Filtered BOM',
        'bom.download.file' => 'Downloaded BOM File',
        'bom.download.json' => 'Downloaded BOM JSON',
        'bom.download.version' => 'Downloaded BOM Version',
        'bom.download' => 'Downloaded BOM Matrix',
        'bom.generateMatrix' => 'Generated BOM Matrix',
        'bom.audit.graph' => 'Viewed BOM Audit Graph',
        'bom.versionHistory' => 'Viewed BOM Version History',
        'crm.BOM.BOM-SourceEngineer.auditBOM' => 'Viewed BOM Audit Report',
        'bom.floating_status.show' => 'Viewed BOM Workflow Status',
        'bom.matrix.export' => 'Exported BOM Matrix',

        'rfqs.index' => 'Viewed RFQs',
        'rfqs.create' => 'Opened Create RFQ',
        'rfqs.store' => 'Uploaded RFQ',
        'rfqs.errorhandler' => 'Viewed RFQ Error',
        'rfq.create' => 'Opened RFQ Create',
        'rfq.send' => 'Sent RFQ',
        'supplierConfig.form' => 'Opened Supplier Config',
        'supplierConfig.submitForm' => 'Submitted Supplier Config',
        'supplier-quotes.view' => 'Viewed Supplier Quote',
        'supplier-quote.index' => 'Viewed Supplier Quote',
        'qw.create' => 'Opened QW Upload',
        'qw.store' => 'Uploaded QW',

        'suppliers.index' => 'Viewed Suppliers',
        'suppliers.create' => 'Opened Create Supplier',
        'suppliers.store' => 'Created Supplier',
        'suppliers.edit' => 'Opened Edit Supplier',
        'suppliers.update' => 'Updated Supplier',
        'suppliers.destroy' => 'Deleted Supplier',

        'smtp-details.index' => 'Viewed MFR',
        'smtp-details.create' => 'Opened Create MFR',
        'smtp-details.store' => 'Created MFR',
        'smtp-details.edit' => 'Opened Edit MFR',
        'smtp-details.update' => 'Updated MFR',
        'smtp-details.destroy' => 'Deleted MFR',

        'tickets.index' => 'Viewed Tasks',
        'tickets.create' => 'Opened Create Task',
        'tickets.store' => 'Created Task',
        'tickets.edit' => 'Opened Edit Task',
        'tickets.update' => 'Updated Task',
        'tickets.destroy' => 'Deleted Task',

        'workflows.index' => 'Viewed Workflows',
        'workflows.create' => 'Opened Create Workflow',
        'workflows.store' => 'Created Workflow',
        'workflows.edit' => 'Opened Edit Workflow',
        'workflows.update' => 'Updated Workflow',
        'workflows.destroy' => 'Deleted Workflow',

        'invoices.index' => 'Viewed Invoices',
        'invoices.create' => 'Opened Create Invoice',
        'invoices.store' => 'Created Invoice',
        'invoices.edit' => 'Opened Edit Invoice',
        'invoices.update' => 'Updated Invoice',
        'invoices.destroy' => 'Deleted Invoice',

        'payments.index' => 'Viewed Payments',
        'payments.create' => 'Opened Create Payment',
        'payments.store' => 'Created Payment',
        'payments.edit' => 'Opened Edit Payment',
        'payments.update' => 'Updated Payment',
        'payments.destroy' => 'Deleted Payment',
    ],
];
